FROM node:18

WORKDIR /app

EXPOSE 8000

COPY /json-server /app/json-server

# важная переменная!!!!!!
ENV NODE_PATH=/app


RUN npm config set registry  https://registry.npmjs.org
RUN npm install json-server@0.17.2 jsonwebtoken

# запускает и ждет выполнения команды
# RUN node json-server/index.js

ENTRYPOINT [ "node", "json-server/index.js" ]


